Remove code to set up SauceLabs tests
This fixes acceptance tests. They broke because the
nsidc_config_injector gem was removed in [pull request #20][0]. The gem
was needed to get credentials to run tests on SauceLabs, and that
functionality was removed from the task runner in 3d434f8.

========================================================================

[Jenkins output from failing build][1]:

```
Started by upstream project "ade_search_A06_Integration_Provision" build number 36
originally caused by:
 Started by upstream project "ade_search_A05_Integration_Run_Unit_Tests" build number 37
 originally caused by:
  Started by upstream project "ade_search_A04_Integration_Check_Syntax" build number 40
  originally caused by:
   Started by upstream project "ade_search_A03_Integration_Install_Dependencies" build number 40
   originally caused by:
    Started by user anonymous
Building in workspace /var/lib/jenkins/workspaces/ade_search/integration
Starting xvnc
[integration] $ vncserver :33 -localhost -nolisten tcp

New 'vsnowload:33 (jenkins)' desktop is vsnowload:33

Starting applications specified in /var/lib/jenkins/.vnc/xstartup
Log file is /var/lib/jenkins/.vnc/vsnowload:33.log

[integration] $ /bin/sh -xe /tmp/hudson7652952194802222377.sh
+ grunt test:acceptance --environment=integration --project=ade_search
Loading "connect_proxy.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined

Running "shell:cucumber" (shell) task
cannot load such file -- nsidc/config_injector_client (LoadError)
/var/lib/jenkins/workspaces/ade_search/integration/spec/cucumber/features/support/enhanced.rb:4:in `require'
/var/lib/jenkins/workspaces/ade_search/integration/spec/cucumber/features/support/enhanced.rb:4:in `<top (required)>'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/rb_support/rb_language.rb:122:in `load'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/rb_support/rb_language.rb:122:in `load_code_file'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:82:in `each'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime.rb:183:in `load_step_definitions'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime.rb:42:in `run!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/cli/main.rb:47:in `execute!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/bin/cucumber:13:in `<top (required)>'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/bin/cucumber:23:in `load'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/bin/cucumber:23:in `<main>'
Warning: Command failed: /bin/sh -c URL=http://integration.nsidc.org//acadis/search bundle exec cucumber spec/cucumber/features --tags @ade_search --format pretty -r spec/cucumber/features/support -r spec/cucumber/features/step_definitions -r spec/cucumber/features/page_objects
cannot load such file -- nsidc/config_injector_client (LoadError)
/var/lib/jenkins/workspaces/ade_search/integration/spec/cucumber/features/support/enhanced.rb:4:in `require'
/var/lib/jenkins/workspaces/ade_search/integration/spec/cucumber/features/support/enhanced.rb:4:in `<top (required)>'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/rb_support/rb_language.rb:122:in `load'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/rb_support/rb_language.rb:122:in `load_code_file'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:180:in `load_file'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:83:in `block in load_files!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:82:in `each'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime/support_code.rb:82:in `load_files!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime.rb:183:in `load_step_definitions'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/runtime.rb:42:in `run!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/lib/cucumber/cli/main.rb:47:in `execute!'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/gems/cucumber-1.3.8/bin/cucumber:13:in `<top (required)>'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/bin/cucumber:23:in `load'
/var/lib/jenkins/workspaces/ade_search/integration/vendor/bundle/ruby/1.9.1/bin/cucumber:23:in `<main>'
 Use --force to continue.

Aborted due to warnings.
Build step 'Execute shell' marked build as failure
Terminating xvnc.
$ vncserver -kill :33
Killing Xvnc4 process ID 4922
Finished: FAILURE
```

[0]: https://bitbucket.org/nsidc/search-interface/pull-request/20/
[1]: http://ci.ade_search.apps.int.nsidc.org:8080/job/ade_search_A07_Integration_Run_Acceptance_Tests/38/console